# Generated by Django 4.0.2 on 2022-02-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_phoro_menu_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
