# Generated by Django 4.0.2 on 2022-02-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_restaurant_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='distance',
        ),
    ]
